### ISSUE TITLE
Lambda async functions with await response

### ISSUE THREAD

**Issue by wesklei** [honeybadger-io/honeybadger-node#112]
Hi!

I'm trying to add honeybadger  in my serverless project and ended with an issue related to async lambda functions using RequestResponse invoke.  If I invoke my function using the code bellow the function hangs forever, it runs successfully but nothing is returned and the request keeps awaiting.
```
let params = {
        FunctionName: functionName,
        InvocationType: "RequestResponse",
        ....
    };
...
lambda.invoke(params);
...
```

My function declaration follow this pattern
```
const handler = async (params) => {
  ....
}

export default Honeybadger.lambdaHandler(handler);
```

I didn't found any example for request response, can you help me understand why my async function isn't working?

thanks!

ps: All my other functions that use Event invoke works.

**Comment by joshuap** [comment]
@wesklei I'm not sure off the top of my head why that would be failing. To be clear, the same function works with Event, but doesn't work with `RequestResponse`? Could you link any packages you are using to call the invoke API? I'll see if I can reproduce.

**Comment by wesklei** [comment]
thanks @joshuap 

I haven't tried the same function using Event yet. I have 6 functions that uses Event and work with Honeybadger, and I have 2 functions that use RequestResponse and don't

After I opened the ticket I've noticed the same with another case using Step Functions with Map. Perhaps the issue is related, since the map will wait for the step completion (probably behind has some sort of request response). In that case I have the following step function config

```
stepFunctions:
  validate: true
  stateMachines:
    cacheMapMachine:
      type: EXPRESS
      name: cacheMapMachine
      definition:
        StartAt: mapped_cache_generator_task
        States:
          mapped_cache_generator_task:
            Type: Map
            Next: EndState
            ItemsPath: "$.queueIds"
            Parameters:
              "queueIds.$": "$$.Map.Item.Value"
            Iterator:
              StartAt: CacheGeneratorMapTask
              States:
                CacheGeneratorMapTask:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [CacheDashgenerateLambdaFunction, Arn]
                  End: true
          EndState:
            Type: Task
            Resource:
              Fn::GetAtt: [PreDashcacheDashlooperLambdaFunction, Arn]
            End: true
```
What happens is that the CacheDashgenerateLambdaFunction complete it's execution and instead of finish and invoke PreDashcacheDashlooperLambdaFunction, it hangs forever


Right now I overcome all this by wrapping my handlers with try catch and manually invoking Honeybadger.notify, not great but it works
